name: Deploy to Github Page

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: Fetch Airtable data
        run: yarn fetch
        env:
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
          AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
      - name: Build
        run: yarn build
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: resolutioncon.com
